version: '3.8'

services:
  
  # Database - Mongo DB
  db:
    image: mongo
    container_name: db
    environment:
      MONGO_INITDB_DATABASE: government_catnip
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
#      - ./init-mongodb/data:/tmp/data — contains a JSON file with an array
  
  app:
    build: .
    container_name: fast

    restart: always
    ports:
      - "8000:5000"
    volumes:
      - ./app:/app